config/routes.rb
Rails.application.routes.draw do
  resources :repositories do
    collection do
      get :get_repositories_by_language
    end
  end

  get "home/index"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repository.rb
class Repository < ApplicationRecord
  after_initialize :validate_repository, unless: :persisted?

  validates_presence_of :repo_name, :description

  def validate_repository
    if !Repository.where(repo_name: self.repo_name,
                         language: self.language).exists?
      self.save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy]

  # GET /repositories
  # GET /repositories.json
  def index
    get_repositories_by_language(params[:language].to_s).each do |repo|
      Repository.new(repo_name: repo.name,
                     description: repo.description,
                     language: repo.lang)
    end

    @repositories = Repository.where("lower(language) = ?", params[:language].downcase)
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
  end

  # GET /repositories/new
  def new
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories
  # POST /repositories.json
  def create
    @repository = Repository.new(repository_params)

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: "Repository was successfully created." }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repositories/1
  # PATCH/PUT /repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: "Repository was successfully updated." }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url, notice: "Repository was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def get_repositories_by_language(language)
    @repositories = GitTrend.get(language)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_repository
    @repository = Repository.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def repository_params
    params.fetch(:repository, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/home/index.html.erb
<div class="container-fluid bg-2 text-center">
    <h1> Welcome to Git Fetcher :)</h1>
    <h3>What Am I?</h3>
    <p>A web-app created to search good repositories on Github!</p>
    <br/>
    <div>
        <p> Pick one: </p>
        <div class="col">
            <%= link_to "Ruby", repositories_path(:language => "Ruby"), method: :get, class: 'btn btn-language btn-danger btn-lg' %>
            <%= link_to "Elixir", repositories_path(:language => "Elixir"), method: :get, class: 'btn btn-language btn-primary btn-lg' %>
            <%= link_to "JavaScript", repositories_path(:language => "JavaScript"), method: :get, class: 'btn btn-language btn-info btn-lg' %>
            <%= link_to "Swift", repositories_path(:language => "Swift"), method: :get, class: 'btn btn-language btn-warning btn-lg' %>
            <%= link_to "GO", repositories_path(:language => "GO"), method: :get, class: 'btn btn-language btn-success btn-lg' %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Git Fetcher</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <div> 
      <%= yield %>
    <div>
  </body>
</html>

app/views/repositories/_form.html.erb
<%= form_with(model: repository, local: true) do |form| %>
  <% if repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% repository.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing Repository</h1>

<%= render 'form', repository: @repository %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<div class="container-fluid bg-2 text-center">
  <h1>Repositories <%= params[:language] %></h1>
  <h5>Total of Repositories <%= @repositories.count unless @repositories.blank? %> <h5>
  <%= button_to "Back to Home", '/', method: :get, class: 'btn btn-link' %>
  <br/>
   <br/>
  <div class="row justify-content-center">
  <% if !@repositories.blank? %>
    <% @repositories.each do |repo|%>

      <div class="text-center card" style="width: 30rem; margin: 10px;">
        <div class="card-body">
          <a href='https://www.github.com/<%=repo.repo_name%>' target="_blank" class="btn btn-link"><h5 class="card-title"><%= repo.repo_name %></h5></a>
          
          <p class="card-text"><%= repo.description %></p>
        </div>
      </div>
    <% end %>
   <% end %>   
   </div> 
<div>

app/views/repositories/new.html.erb
<h1>New Repository</h1>

<%= render 'form', repository: @repository %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>